name: deployment-1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: cloning-code
      uses: actions/checkout@v3
    - name: install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
    - name: Build
      run: npm run build
    - name: Deploy
      run: echo "your application is deploying"
     


